services:
  - type: web
    name: upolobdhi-reviews-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://kihobe45_db_user:r2vkyzitfuexJmwa@cluster0.sssabcc.mongodb.net/upolobdhi_reviews?retryWrites=true&w=majority&appName=Cluster0
      - key: CORS_ORIGINS
        value: https://teamupolobdhi.vercel.app
